### PR TITLE
Snorql Version Upgrade

### PR DESCRIPTION
**Pull request by prajain12**
Signed-off-by: Prakul Jain <prakul.jain@udaan.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Backward compatibility

- [ ] snorql-extensions
- [ ] snorql-framework

### CODE REVIEW

**Comment by prajain12** [comment]
Hi @lokeshdevnani 
Had few queries
1. What must be the updated version of Snorql? The current version is 0.5.7-SNAPSHOT
2. As this release contains too many changes, should we do this incrementally?

**Comment by lakshmi-udaan** [comment]
@prajain12 I think we should extract out `snorql-framework` related changes into a separate PR first

**Review by lakshmi-udaan — CHANGES_REQUESTED** [review]
@prajain12 I think we should extract out snorql-framework related changes into a separate PR first
CC: @lokeshdevnani

**Comment by prajain12** [comment]
> @prajain12 I think we should extract out snorql-framework related changes into a separate PR first CC: @lokeshdevnani

That is in progress. Opened https://github.com/udaan-com/snorql/pull/77 for the same. Testing pending. Any suggestions on how can I move ahead to test it?

**Pull request closed without merging**
